name: Java CI with Maven - Test and package

on:
  pull_request:
    branches: [main]

jobs:
  checkout-setup-java:
    name: Checkout and Setup Java with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  repository
        uses: actions/checkout@v4.1.6
      - name: Setup Java
        uses: ./
        id: setup-java
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Run maven
        run: mvn -B package
