name: Documentation

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Run documentation
        run: mvn -B javadoc::javadoc
      - name: Build documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/reports/javadoc